##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: "/home/gaurav/Operating Room Logestics/fetch_description/robots/fetch/fetch.usd"
    usd_robot_root: "/fetch"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "/home/gaurav/fetch_ws/src/fetch/urdf/fetch.urdf"
    asset_root_path: "/home/gaurav/fetch_ws/src/fetch/meshes"
    
    base_link: "base_link"
    ee_link: "gripper_link"
    link_names: null
    lock_joints: null
    extra_links: null

    
    collision_link_names: null # List[str]
    collision_spheres: null #
    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: {} # Dict[str, List[str]]
    self_collision_buffer: {} # Dict[str, float]

    use_global_cumul: True
    mesh_link_names: null # List[str]
    external_asset_path: null # Use this to add path for externally located assets/robot folder.

    cspace:
      joint_names: ['torso_lift_joint', 'shoulder_pan_joint', 'shoulder_lift_joint', 'upperarm_roll_joint', 'elbow_flex_joint', 'forearm_roll_joint', 'wrist_flex_joint', 'wrist_roll_joint'] # List[str]
      retract_config: [-1.3927, 1.2910, 0.2602, 1.9277, 0.0000, 1.3724, -0.1908, 0] # List[float]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      max_jerk: 500.0
      max_acceleration: 15.0
      position_limit_clip: 0.1
