robot_cfg:
  kinematics:
    use_usd_kinematics: False
    isaac_usd_path: "config/fetch_manip/fetch_manip.usd"
    usd_robot_root: "/fetch"
    usd_flip_joints: ["shoulder_pan_joint", "shoulder_lift_joint", "upperarm_roll_joint",
                      "elbow_flex_joint", "forearm_roll_joint", "wrist_flex_joint", "wrist_roll_joint"]
    usd_flip_joints: {
      "shoulder_pan_joint": "Z",
      "shoulder_lift_joint": "Z",
      "upperarm_roll_joint": "Z",
      "elbow_flex_joint": "Z",
      "forearm_roll_joint": "Z",
      "wrist_flex_joint": "Z"
    }

    usd_flip_joint_limits: []
    urdf_path: "config/fetch_manip.urdf"
    asset_root_path: "/home/siddharth/fetch_ros/fetch_description"
    base_link: "base_link"
    ee_link: "gripper_link"
    collision_link_names:
      [
        "base_link",
        "head_pan_link",
        "torso_base_link",
        "shoulder_pan_link",
        "shoulder_lift_link",
        "upperarm_roll_link",
        "elbow_flex_link",
        "forearm_roll_link",
        "wrist_flex_link",
        "wrist_roll_link",
        "gripper_link",
        "attached_object",

      ]
    collision_spheres: "config/fetch_mesh.yml"
    collision_sphere_buffer: 0.0025
    extra_collision_spheres: {"attached_object": 20}

    # extra_collision_spheres: {"gripper_link": 2}
    use_global_cumul: True
    self_collision_ignore:
      {
        # "shoulder_pan_link": ["shoulder_lift_link", "upperarm_roll_link", "torso_lift_link"],
        "base_link": ["head_pan_link", "head_tilt_link", "torso_base_link"],
        "head_pan_link": ["shoulder_pan_link", "torso_base_link"],
        "torso_base_link": ["shoulder_pan_link", "shoulder_lift_link"],
        "shoulder_pan_link": ["torso_base_link", "shoulder_lift_link"],
        "shoulder_lift_link": ["upperarm_roll_link", "elbow_flex_link"],
        "upperarm_roll_link": ["elbow_flex_link", "forearm_roll_link"],
        "elbow_flex_link": ["forearm_roll_link", "wrist_flex_link"],
        "forearm_roll_link": ["wrist_flex_link", "wrist_roll_link"],
        "wrist_flex_link": ["wrist_roll_link", "gripper_link"],
        "wrist_roll_link": ["gripper_link", "attached_object"],
        "gripper_link": ["wrist_roll_link", "wrist_flex_link", "attached_object"],
      }
    self_collision_buffer:
      {
        "base_link": 0.0,
        "head_pan_link": 0.005,
        "torso_base_link": 0.00,
        "shoulder_pan_link": 0.0,
        "shoulder_lift_link": 0.00,
        "upperarm_roll_link": 0.0,
        "elbow_flex_link": 0.0,
        "forearm_roll_link": 0.0,
        "wrist_flex_link": 0.0,
        "wrist_roll_link": 0.0,
        "gripper_link": 0.0,
        "attached_object": 0.0,
      }

    mesh_link_names:
      [
        "base_link",
        "head_pan_link",
        "torso_base_link",
        "shoulder_pan_link",
        "shoulder_lift_link",
        "upperarm_roll_link",
        "elbow_flex_link",
        "forearm_roll_link",
        "wrist_flex_link",
        "wrist_roll_link",
        "gripper_link",
      ]
    # lock_joints: {"r_gripper_finger_joint": 0.05, "l_gripper_finger_joint": 0.05}
    # extra_links: {"gripper_link": {"parent_link_name": "wrist_roll_link",
    #                                "link_name": "gripper_link", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
    #                                "joint_name": "gripper_joint"}}
    extra_links: {"attached_object":{"parent_link_name": "gripper_link" ,
    "link_name": "attached_object", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
    "joint_name": "attach_joint" }}
    
    cspace:
      joint_names: ["shoulder_pan_joint", "shoulder_lift_joint", "upperarm_roll_joint", "elbow_flex_joint", "forearm_roll_joint", "wrist_flex_joint", "wrist_roll_joint"]
      retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

      null_space_weight: [1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1]
      max_acceleration: 10.0
      max_jerk: 300.0
