# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Gripper_controller:
  ros__parameters:
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Arm_controller:
  ros__parameters:
    joints:
      - torso_lift_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity